# how to create an array?

##1-D

In [1]:
import numpy as np # first example
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
b=np.zeros(2)
b

array([0., 0.])

In [5]:
c=np.ones(3)
c

array([1., 1., 1.])

In [6]:
# Creatw an empty array with 2 elements
d=np.empty(3)
d

array([1., 1., 1.])

In [9]:
## Second example
# with range of elements
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [11]:
# with specific range of element
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
#continue...
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#linearly spaced arrays
h=np.linspace(0,10,num=5) #gives use 5 num
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
# specific data types in array
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [20]:
j=np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

In [ ]:
## 2-D array

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
##3-D array

In [25]:
#making and reshaping a 3D array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## numpy _practice_ session

In [1]:
# import this library in j.notebook
import numpy as np

# Creating an array using numpy

In [2]:
food=np.array(["Pakora","samosa","raita"])
food

array(['Pakora', 'samosa', 'raita'], dtype='<U6')

In [7]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [8]:
type(price)

numpy.ndarray

In [9]:
len(food)

3

In [10]:
price[2]

5

In [11]:
price[0:]

array([5, 5, 5])

In [12]:
food[1]

'samosa'

In [13]:
price.mean()

5.0

In [16]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [20]:
# arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# specific arange
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
#specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
#table
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
# line space
np.linspace(0,100, num=7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [29]:
#specify your data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [30]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [31]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [32]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [34]:
b=np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [36]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [38]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

In [ ]:
## 2-D array

In [39]:
a =np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [40]:
b=np.array([[6,7,8,9,10],[10,9,8,7,6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [41]:
c=np.concatenate([a,b])
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [42]:
d=np.concatenate((a,b), axis=0)
d

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [43]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [44]:
a=np.array([[[0,1,2,3],
                        [4,5,6,7]],
                      
                      [[0,1,2,3],
                      [4,5,6,7]],
                      
                      [[0,1,2,3],
                      [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [46]:
# to find the number of dimensions
a.ndim

3

In [ ]:
b=np.array([[5,6,7],
          [8,9,10],
           [11,12,13]])

In [47]:
b.ndim

2

In [48]:
# size means (number of elements)
a.size

24

In [49]:
# shape
a.shape

(3, 2, 4)

In [51]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
# reshape # 3*3=9
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
# convert 1D into 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a.shape

(9,)

In [57]:
#rowwise 2D
b= a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
b.shape

(1, 9)

In [59]:
# column wise
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [60]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [63]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [64]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
a.sum()

45

In [66]:
a.mean()

5.0